insert into Subject (id, name) values (1, N'Toán');
insert into Subject (id, name) values (2, N'Vật lí');
insert into Subject (id, name) values (3, N'Hóa học');
insert into Subject (id, name) values (4, N'Sinh học');
insert into Subject (id, name) values (5, N'Tin học');
insert into Subject (id, name) values (6, N'Ngữ văn');
insert into Subject (id, name) values (7, N'Lịch sử');
insert into Subject (id, name) values (8, N'Địa lí');
insert into Subject (id, name) values (9, N'Ngoại ngữ');
insert into Subject (id, name) values (10, N'Giáo dục công dân');
insert into Subject (id, name) values (11, N'Công nghệ');
insert into Subject (id, name) values (12, N'Thể dục');
insert into Subject (id, name) values (13, N'Giáo dục QP-AN');